# print("Hello world !!!")
# name  = input("Hãy nhập tên của bạn: ")
# age = input("Hãy nhập tuổi của bạn: ")
# print(f"Xin chào bạn {name}")
# print(f"Bạn {age} tuổi")
print(1+1)
print(2*3)
print(8/4)
print(9-5)